settings:
  name: "BlueXP disaster recovery"
  platform: cloud
  internal:
    pdf_enabled: true
    termcheck_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true

sidebar:
  entries:
    - title: BlueXP disaster recovery docs
      url: /index.html
    - section: release-notes
    - section: get-started
    - section: use
    - section: reference
    - section: support
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: BlueXP
  repo: cloud-manager-family
