=== Intelligent proxy support 

The BlueXP Connector supports intelligent proxy. Intelligent proxy is a lightweight, secure, and efficient way to connect your on-premises environment to the BlueXP service. It provides a secure connection between your environment and the BlueXP service without requiring a VPN or direct internet access. This optimized proxy implementation offloads API traffic within the local network.

When a proxy is configured, BlueXP disaster recovery attempts to communicate directly with VMware or ONTAP and uses the configured proxy if direct communication fails.

BlueXP disaster recovery proxy implementation requires port 443 communication between the Connector and any vCenter Servers and ONTAP arrays using an HTTPS protocol. The BlueXP disaster recovery agent within the Connector communicates directly with VMware vSphere, the VC, or ONTAP when performing any actions.
 

For more information about the intelligent proxy for BlueXP disaster recovery, see link:../get-started/dr-setup.html[Set up your infrastructure for BlueXP disaster recovery].

//For more information about the intelligent proxy for BlueXP disaster recovery, see https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-setup.html[Set up your infrastructure for BlueXP disaster recovery].

For more information about the intelligent proxy, see 
https://docs.netapp.com/us-en/bluexp-setup-admin/task-configuring-proxy.html 



=== End the free trial any time

You can stop the free trial at any tine or you can wait until it expires. 

See https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html[Set up licensing].

