=== User roles in BlueXP disaster recovery

BlueXP disaster recovery now employs roles to govern the access that each user has to specific features and actions. 

The service uses the following roles that are specific to BlueXP disaster recovery. 

* *Disaster recovery admin*: Perform any actions in BlueXP disaster recovery.
* *Disaster recovery failover admin*: Perform failover and migrate actions in BlueXP disaster recovery. 
* *Disaster recovery application admin*: Create and modify replication plans and start test failovers. 
* *Disaster recovery viewer*: View information in BlueXP disaster recovery, but cannot perform any actions.

If you are configuring BlueXP disaster recovery for the first time, you must have the *SnapCenterAdmin* permission or have the *Organization Admin* role. 

For details, see  link:../reference/dr-reference-roles.html[User roles and permissions in BlueXP disaster recovery].

//For details, see  https://docs.netapp.com/us-en/bluexp-disaster-recovery/reference/dr-reference-roles.html[User roles and permissions in BlueXP disaster recovery].

=== Other updates in BlueXP disaster recovery 

* Enhanced network discovery
* Scalability improvements:
** Filtering for the required metadata instead of all the details
** Discovery improvements to retrieve and update VM resources faster
** Memory optimization and performance optimization for data retrieval and data updates
** vCenter SDK client creation and pool management improvements

* Stale data management on the next scheduled or manual discovery:
** When a VM is deleted in the vCenter, BlueXP disaster recovery now automatically removes it from the replication plan.
** When a datastore or network is deleted in the vCenter, BlueXP disaster recovery now deletes it from the replication plan and resource group. 
** When a cluster, host, or datacenter is deleted in the vCenter, BlueXP disaster recovery now deletes it from the replication plan and resource group.

* You can now access Swagger documentation in Private mode. 
* In some situations after a failback operation, the iGroup was left behind after the operation completed. This update removes the iGroup if it is stale.


* If the NFS FQDN was used in the replication plan, BlueXP disaster recovery now resolves it to an IP address. This update is useful if the FQDN is not resolvable in the disaster recovery site.

* UI alignment improvements

* Log improvements to capture the vCenter sizing details after the successful discovery