---
sidebar: sidebar
permalink: reference/evs-deploy-guide-install-connector.html
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter 
summary: Introduction of BlueXP disaster recovery using Amazon EVS and Amazon FSx for NetApp ONTAP. While the Connector can be installed in any of your network locations, for BlueXP disaster recovery we recommend that you install the Connector in the DR site. This ensures that in the event of a failure of the primary site, the BlueXP cloud-based console UI continues to have contact with the Connector and can orchestrate the recovery process within that DR site.

---
= Install the BlueXP Connector for BlueXP disaster recovery

:hardbreaks:
:icons: font
:imagesdir: ../media/use/

[.lead]
A BlueXP Connector is NetApp software running in your cloud or on-premises network. It executes the actions that BlueXP needs to perform to manage your data infrastructure. The Connector constantly polls the BlueXP disaster recovery software as a service layer for any actions that it needs to take.

For the BlueXP disaster recovery service, the actions that are performed orchestrate VMware vCenter clusters and ONTAP storage instances using native APIs for each respective service to provide protection for production VMs running in an on-premises location. While the Connector can be installed in any of your network locations, for BlueXP disaster recovery we recommend that you install the Connector in the DR site. This ensures that in the event of a failure of the primary site, the BlueXP cloud-based console UI continues to have contact with the Connector and can orchestrate the recovery process within that DR site.

To use the service, install the Connector in standard mode. To learn more about the types of Connector installations, visit https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html[Learn about BlueXP deployment modes | NetApp Documentation^].

While the Connector is critical to using the service, the installation steps to install the Connector depend on your needs and network configuration. It is beyond the scope of this information to provide specific instructions for installation. 

The simplest method for installing a Connector with Amazon AWS is to use the AWS Marketplace. For details about Connector installation using the AWS Marketplace, see https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-aws-marketplace.html[Create a Connector from the AWS Marketplace | NetApp Documentation^].
