---
sidebar: sidebar
permalink: reference/evs-deploy-guide-config-draas.html
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter 
summary: After the BlueXP Connector has been installed, you need to integrate all the ONTAP storage and VMware vCenter resources that will participate in the DR process.

---

= Configure BlueXP disaster recovery for Amazon EVS overview

:hardbreaks:
:icons: font
:imagesdir: ../media/use/

[.lead]
After you install the BlueXP Connector, you need to integrate all the ONTAP storage and VMware vCenter resources that will participate in the disaster recovery process with BlueXP disaster recovery. 

* link:evs-deploy-guide-config-prereqs.html[Prerequisites for Amazon EVS with BlueXP disaster recovery]
* link:evs-deploy-guide-config-add-arrays.html[Add ONTAP storage arrays to BlueXP disaster recovery]
* link:evs-deploy-guide-enable-draas.html[Enable BlueXP disaster recovery for Amazon EVS]
* link:evs-deploy-guide-config-add-arrays.html[Add vCenter sites to BlueXP disaster recovery]
* link:evs-deploy-guide-add-vcenters.html[Add vCenter clusters to BlueXP disaster recovery]


