---
sidebar: sidebar
permalink: use/evs-deploy-guide-config-prereqs.html
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter 
summary: Introduction of BlueXP disaster recovery using Amazon EVS and Amazon FSxN.

---
= Prerequisites for Amazon EVS

:hardbreaks:
:icons: font
:imagesdir: ../media/use/

[.lead]
There are several prerequisites that need to be satisfied before you continue. 

Specifically, do the following:

[start 1]

. Create a vCenter user account with the specific VMware privileges required for DRaaS to perform the necessary operations. 
+
It is not recommended to use the default administrator@vsphere.com administrator account, but to create a BlueXP disaster recovery specific user account on all vCenter clusters that will participate in the DR process. The specific privileges required are listed in vCenter privileges needed for BlueXP disaster recovery | NetApp Documentation.

. Ensure that all vCenter datastores that will be hosting VMs protected by BlueXP disaster recovery are located on NetApp ONTAP storage resources. The service currently support NFS datastores and VMFS datastores hosted on iSCSI or Fibre Channel connected LUNs.

. Ensure that your Amazon EVS vCenter is connected to an Amazon FSx for NetApp ONTAP storage cluster.

. Ensure that VMware tools are installed on all protected VMs.

. Ensure that your on-premises network is connected to your AWS VPC network using an Amazon approved connection method. It is recommended that you use AWS Direct Connect, AWS Private Link, or an AWS Site-to-Site VPN.
