---
sidebar: sidebar
permalink: use/evs-deploy-guide-introduction.html
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter 
summary: Introduction of BlueXP disaster recovery using Amazon EVS and Amazon FSxN.

---

= Introduction of BlueXP disaster recovery using Amazon Elastic VMware Service and Amazon FSx for NetApp ONTAP

:hardbreaks:
:icons: font
:imagesdir: ../media/use/

[.lead]
Increasingly, customers have become much more dependent on virtualized infrastructures for production compute workloads such as those based on VMware vSphere. As these virtual machines (VMs) have become more critical to their businesses, customers have a need to protect these VMs from the same types of disasters as their physical compute resources. Disaster recovery (DR) solutions currently offered are complex, expensive and resource intensive. NetApp, the largest storage provider used for virtualized infrastructures, has a vested interest in ensuring its customers’ VMs are protected in the same way that we protect ONTAP storage-hosted data of any type. To meet this goal, NetApp has created the BlueXP disaster recovery service.

One of the primary challenges with any DR solution is managing the incremental cost of purchasing, configuring, and maintaining additional compute, network, and storage resources just to provide a DR replication and recovery infrastructure. One popular option for protecting critical on-premises virtual resources is to use cloud-hosted virtual resources as the DR replication and recovery infrastructure. Amazon is one example of such a solution that can provide cost-effective resources that are compatible with NetApp ONTAP hosted VM infrastructures.

Amazon introduced its Amazon Elastic VMware Service (Amazon EVS) that enables VMware Cloud Foundation within your virtual private cloud (VPC). Amazon EVS provides the resilience, and performance of AWS alongside the familiar VMware software and tools enabling Amazon EVS vCenters to be integrated as an extension of your on-premises virtualized infrastructure.

While Amazon EVS comes with included storage resources, using native storage can reduce its effectiveness for organizations with storage-heavy workloads. In these cases, teaming Amazon EVS with Amazon FSx for NetApp ONTAP storage (Amazon FSxN) can provide a more flexible storage solution in these cases. In addition, when you are also using NetApp ONTAP storage solutions on-premises to host your VMware infrastructure, using Amazon EVS with Amazon FSxN means you get best-in-class data interoperability and protection features between your on-premises and cloud-hosted infrastructures.
