---
sidebar: sidebar
permalink: use/manage.html
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter
summary: The NetApp BlueXP disaster recovery is a cloud-based disaster recovery service that automates disaster recovery workflows.
---

= Manage sites, plans, datastores and virtual machines information
:hardbreaks:
:icons: font
:imagesdir: ../media/use/

[.lead]
You can get a quick glance of all your Disaster recovery resources or look at each in detail: 

* Dashboard
* Sites
* Replication plans
* Datastores
* Virtual machines
* Resource groups

== View the BlueXP disaster recovery Dashboard

Use the Dashboard to get an at-a-glance view of all the BlueXP disaster recovery resources and activities. The Activity pane shows up-to-date job operation activity. 

.Steps 

. From the BlueXP left nav, select *Protection* > *Disaster recovery* > *Virtual machines*. 
. From the top menu, select *Dashboard*. 

. Explore all disaster recovery plans, compliance, vCenters, virtual machines, and resource groups in the Dashboard.

. To view the resource, select *View*. 
. To view all resource groups, select *View resource groups*. 

== Manage vCenter sites
You can edit the vCenter site name the the site type (on-premises or AWS).

.Steps 

. From the top menu, select *Sites*. 
. Edit the vCenter site name and site type. 

== Manage replication plans 

You can disable, enable and delete replication plans. 

* If you want to pause a replication plan temporarily, you can disable it and later enable it. 
* If you no longer need the plan, you can delete it.

.Steps 

. From the top menu, select *Replication plans*. 
. To view the plan details, select the *Actions* … icon and select *View plan details*.  

. Do any of the following: 
+
* To edit the plan details (change the recurrence), select the *Plan details* tab and select the *Edit* icon to the right. 
* To edit the resource mappings, select the *Failover mapping* tab and select the *Edit* icon. 
* To add or edit the virtual machines, select the *Virtual machine* tab and select the *Edit* icon. 

. To perform actions with the plan, select the *Actions* … menu at the top and select any of the options, such as *Test failover*, *Fail over*, *Fail back*, *Disable*, *Enable*, or *Delete*. 

== View datastores information 

You can view information about how many datastores exist on the source and on the target. 

.Steps 

. From the top menu, select *Datastores*. 
. View the datastores information. 

== View virtual machines information 

You can view information about how many virtual machines exist on the source and on the target along with CPU, memory, and available capacity. 

.Steps 

. From the top menu, select *Virtual machines*. 
. View the virtual machines information. 

== Manage resource groups 

While you can add a resource group as part of creating a replication plan, you might find it more convenient to add the groups separately and later use those groups in the plan. 

You can also edit and delete resource groups. 

.Steps 

. From the top menu, select *Resource groups*. 
. To add a resource group, select *Add group*.  
. To perform actions with the resource group, select the *Actions* … menu at the top and select any of the options, such as *Edit resource group* or *Delete resource group*. 