---
sidebar: sidebar
permalink: use/sites-add.html
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter
summary: The NetApp BlueXP disaster recovery is a cloud-based disaster recovery service that automates disaster recovery workflows.
---

= Add vCenter sites
:hardbreaks:
:icons: font
:imagesdir: ../media/use/

[.lead]
Before you can create a disaster recovery plan, you need to add a primary vCenter site and a target vCenter disaster recovery site to BlueXP. 

After they are added, BlueXP disaster recovery performs a deep discovery of the vCenter environments, including vCenter clusters, ESXi hosts, datastores, storage foot print, virtual machine details, SnapMirror replicas, and virtual machine networks.

.Steps

. Log in to BlueXP and select *Protection* > *Disaster recovery* > *Virtual machines* from the left nav. 
+
You’ll land on BlueXP disaster recovery Dashboard page. When you first start with the service, you need to add vCenter information. Later, the Dashboard displays data about your sites and replication plans. 

. Select *Discover vCenter servers* to enter information about the source vCenter site.  

. Add a site, select the BlueXP Connector, and provide vCenter credentials. 
+
A VMC is one of the sites.

. To accept self-signed certificates for the source vCenter, check the box. 
+
NOTE: Self-signed certificates are not as secure as other certificates. If your vCenter is *NOT* configured with CA signed certificates, you should check this box; otherwise, the connection to the vCenter will not work.  

. Select *Add*. 
+
Next, you will add a target vCenter. 

. Choose the target site and the location. If the target is cloud, select *AWS*.  

. Select *Add*. 
+
The source and target vCenters appear on the list of sites. 

. To see the progress of the operation, from the top menu, select *Job monitoring*. 