---
sidebar: sidebar
permalink: get-started/dr-faq.html
keywords: disaster recovery faq, disaster recovery frequently asked questions
summary: This FAQ can help if you're just looking for a quick answer to a question.
---

= Frequently asked questions for BlueXP disaster recovery
:hardbreaks:
:icons: font
:imagesdir: ../media/

[.lead]
This FAQ can help if you're just looking for a quick answer to a question.



*What's the BlueXP disaster recovery URL?*
For the URL, in a browser, enter: https://console.bluexp.netapp.com/[https://console.bluexp.netapp.com/^] to access the BlueXP console. 


//*Do you need a license to use BlueXP disaster recovery?*
//A BlueXP disaster recovery license is required for complete access. However, you can try it out with the free trial. 

//For details about setting up licensing for BlueXP disaster recovery, refer to link:../get-started/dr-licensing.html[Set up BlueXP disaster recovery licensing].


*How do you access BlueXP Disaster recovery?*
BlueXP disaster recovery does not require any enablement. The disaster recovery option automatically appears on the BlueXP left navigation.  

//*Does this service support a cloud-to-cloud scenario?*  
//This preview will support a cloud-to-cloud scenario for cross-region replication using VMware Cloud on AWS with Amazon FSx for NetApp ONTAP in separate AWS regions.  