---
sidebar: sidebar
permalink: get-started/dr-login.html
keywords: bluexp login, disaster recovery log in
summary: Get started with BlueXP disaster recovery by accessing the service in BlueXP.
---

= Access BlueXP disaster recovery
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

[.lead]
You use NetApp BlueXP to log in to the BlueXP disaster recovery service. 

To log in to BlueXP, you can use your NetApp Support Site credentials or you can sign up for a NetApp cloud login using your email and a password. https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-logging-in.html[Learn more about logging in^].

.Steps

. Open a web browser and go to the https://console.bluexp.netapp.com/[BlueXP console^].
+ 
The NetApp BlueXP login page appears.

. Log in to BlueXP. 
. From the BlueXP left navigation, select *Protection* > *Disaster recovery*. 
+
The BlueXP disaster recovery Dashboard appears.

+
If you don't have a BlueXP Connector or it's not the one for this beta, you might need to contact NetApp Support or follow messages to sign up for this beta. 

* If you are new to BlueXP and haven't used any Connector, when you select "Disaster recovery", a message appears about signing up. Go ahead and submit the form. NetApp will contact you about your beta request. 
* If you are a BlueXP user an an existing Connector, when you select "Disaster recovery", a message appears about signing up. 
* If you are already participating in the beta, when you select "Disaster recovery", you can proceed with the service. 
