---
sidebar: sidebar
permalink: get-started/dr-prerequisites.html
keywords: what are bluexp disaster recovery requirements, disaster recovery prerequisites
summary: Get started with BlueXP disaster recovery by verifying support for your environment, network access, login and web browser.
---

= BlueXP disaster recovery prerequisites
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

[.lead]
Get started by verifying the readiness of your operational environment, login, network access, and web browser.

Before using BlueXP disaster recovery, you should ensure that your environment meets the following requirements: 

== ONTAP storage prerequisites

* Source and destination clusters must have a peer relationship. 
* SVM-to-host disaster recovery volumes must exist on the destination cluster.
* The source SVM and destination SVM must have a peer relationship. 
+
NOTE: Disaster recovery volumes in the destination SVM or SVMs should not be created ahead of time. BlueXP disaster recovery will create the destination volumes as needed for the replication plan. 

== VMware vCenter clusters and/or VMware Cloud Foundations SDDS prerequisites

All VMware clusters that you want BlueXP disaster recovery to manage must be hosted on ONTAP volumes using one of the following protocols: 

* NFS 
* VMFS using the iSCSI protocol (currently in a technology preview)

== On-premises to AWS infrastructure prerequisites
* Amazon FSx for NetApp ONTAP: 
** An Amazon FSx for NetApp ONTAP instance to host VMware DR datastores must exist in your VPC. Refer to Amazon FSx for ONTAP documentation on https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/getting-started-step1.html[how to get started^]. 
** All ONTAP storage prerequisites, cited on this page, must be applied to cluster and SVM peering and SVM creation. 

* VMware Cloud Foundations SDDC: 
** A VMware software-defined data center (SDDC) instance must exist with appropriate access credentials. 
** In the VMware Cloud Console, use the service roles of Administrator and NSX Cloud Administrator. Also use the organization owner for the Organization role. Refer to https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/vmware-cloud-ontap.html[Using VMware Cloud Foundations with AWS FSx for NetApp ONTAP documentation^]. 

* Link the VMware Cloud SDDC with Amazon FSx for NetApp ONTAP. Refer to https://vmc.techzone.vmware.com/fsx-guide#overview[VMware Cloud on AWS integration with Amazon FSx for NetApp ONTAP deployment information^].


== BlueXP prerequisites

* Amazon FSx for ONTAP and AWS credentials must be added to the BlueXP workspace working environment that will be used to manage BlueXP disaster recovery.

* A BlueXP Connector must be set up in BlueXP. 
** BlueXP disaster recovery works only with the standard mode Connector deployment. 
** On-premises to on-premises disaster recovery: We recommend that you install the BlueXP on-premises Connector to the disaster recovery site. Refer to https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-on-prem.html[Install and set up a Connector on premises^].
** On-premises to AWS: Install the BlueXP Connector for AWS onto your AWS VPC. Refer to https://docs.netapp.com/us-en/bluexp-setup-admin/concept-install-options-aws.html[Connector installation options in AWS^].
** The on-premises and cloud Connector should have connectivity to both the on-premises and VMware Cloud (VMC) VCenter with ESXis. This enables the backup, failover, failback and migration features to work properly with the needed networking and script features.
+ 
The BlueXP Connector requires credentials for both the source and target vCenter servers. Refer to the https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-quick-start-standard-mode.html[BlueXP Quick start^] and https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-networking-saas-console.html[BlueXP networking information^]. 
* Follow the BlueXP prerequisites for https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-standard-mode.html[Getting started with BlueXP in standard mode^]. 

== Workload prerequisites
To ensure that application-consistency processes are successful, ensure the following prerequisites are met: 

* Ensure that VMware tools (or Open VM tools) are running on the VMs that will be protected. 
* For Windows VMs running SQL or Oracle or both, the databases should have their VSS Writers enabled and the databases should be in a stable state. 
* Oracle databases that are running on a Linux operating system should have the operating system user authentication enabled for the Oracle database SYSDBA role.  



