---
sidebar: sidebar
permalink: get-started/dr-setup.html
keywords: bluexp, disaster recovery, aws, amazon web services, amazon fsx for netapp ontap
summary: To use BlueXP disaster recovery, perform a few steps to set it up.    
---

= Set up your infrastructure for BlueXP disaster recovery
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

[.lead]
To use BlueXP disaster recovery, perform a few steps to set it up both in Amazon Web Services (AWS) and in BlueXP.  

TIP: Review link:../get-started/dr-prerequisites.html[prerequisites] to ensure that your environment is ready.


 
== Set up VMware Cloud Foundations for AWS SDDC

* Create an Amazon FSx for ONTAP file system. Provision and configure FSx for ONTAP. Amazon FSx for NetApp ONTAP is a fully managed service that provides highly reliable, scalable, high-performing, and feature-rich file storage built on the popular NetApp ONTAP file system. 

* Follow the steps at this https://docs.netapp.com/us-en/netapp-solutions/ehc/aws/aws-native-overview.html[link^] and here https://docs.netapp.com/us-en/bluexp-fsx-ontap/start/task-getting-started-fsx.html[Quick start for Amazon FSx for NetApp ONTAP] to provision and configure FSx for NetApp ONTAP.

* Add Amazon FSx for NetApp ONTAP to the working environment, and add AWS credentials for FSx for ONTAP. 

* In AWS, you'll need to do the following steps: 

** Deploy and configure VMware Cloud on AWS.

** Use a VMware account and provision the software-defined data center (SDDC). Ensure that the SDDC has connectivity with FSx for ONTAP.

=== Deploy VMware Cloud
https://www.vmware.com/products/vmc-on-aws.html[VMware Cloud on AWS^] provides a cloud-native experience for VMware-based workloads in the AWS ecosystem. Each VMware software-defined data center (SDDC) runs in an Amazon Virtual Private Cloud (VPC) and provides a full VMware stack (including vCenter Server), NSX-T software-defined networking, vSAN software-defined storage, and one or more ESXi hosts that provide compute and storage resources to the workloads. 

To configure a VMC environment on AWS, follow the steps at this https://docs.netapp.com/us-en/netapp-solutions/ehc/aws/aws-setup.html[link^]. A pilot-light cluster can also be used for disaster recovery purposes.



== Create a Connector in BlueXP
You need to reach out to your NetApp Sales Rep to try out the BlueXP disaster recovery service. Then, when you use the BlueXP Connector, it will include the appropriate capabilities for the disaster recovery service. 

To create a Connector in BlueXP before using the service, refer to the BlueXP documentation that describes https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html[how to create a connector^]. 

For on-premises to on-premises, use the BlueXP on-premises Connector. For on-premises to AWS, use the BlueXP AWS Connector, which has access to the source on-premises vCenter and the destination on-premises vCenter.

== Add a BlueXP account

In BlueXP, if you don't already have an account, you'll need to add an account. Refer to the https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-netapp-accounts.html[BlueXP documentation on how to add an account^]. 

//=== Configure SnapMirror for Amazon FSx for NetApp ONTAP

//The next step is to set up configure SnapMirror for Amazon FSx in BlueXP. 

//Refer to https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/use/task-creating-fsx-working-environment.html[how to set up an FSx for ONTAP working environment^].

//. Add Amazon FSx for NetApp ONTAP to the working environment that is used to manage BlueXP disaster recovery. 
//. Ensure the following: 
//** The source and destination clusters are peered. 
//** The destination SVM is created. 
//** The source and destination SVMs are peered. 
//** The SnapMirror relationship with the ONTAP cluster is in place and that it has a destination of FSx for NetApp ONTAP. 

//. In BlueXP, discover the provisioned FSx for NetApp ONTAP on an AWS instance and replicate the specified datastore volumes from an on-premises environment to FSx for NetApp ONTAP with the appropriate frequency and NetApp Snapshot copy retention. 

== Add the on-premises ONTAP storage

Add the on-premises ONTAP storage working environment to BlueXP. Add your ONTAP clusters (on-prem or FSx) to BlueXP and ensure the following: 

* The source and destination clusters are peered. 
* The destination SVM is created. 
* The source and destination SVMs are peered. 

See https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html[Discover on-premises ONTAP clusters^].

== Set up licensing 

With BlueXP disaster recovery, you can sign up for a 90-day free trial.

You can purchase a pay-as-you-go (PAYGO) subscription with AWS Marketplace or Bring Your Own License (BYOL), which is a NetApp License File (NLF).  

Refer to link:../get-started/dr-licensing.html[Set up BlueXP disaster recovery licensing].



