---
sidebar: sidebar
permalink: get-started/dr-setup.html
keywords: bluexp, disaster recovery, aws, amazon web services
summary: To use BlueXP disaster recovery, perform a few steps to set it up.    
---

= Set up BlueXP disaster recovery
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

[.lead]
To use BlueXP disaster recovery, perform a few steps to set it up both in Amazon Web Services (AWS) and in BlueXP.  

TIP: Review link:../get-started/dr-prerequisites.html[prerequisites] to ensure that your environment is ready.



== Set up AWS
In AWS, you'll need to do the following steps: 

* Deploy and configure VMware Cloud on AWS.
* Create an Amazon FSx for ONTAP file system. Provision and configure FSx for ONTAP. 
* Use a VMware account and provision the software-defined data center (SDDC). Ensure that the SDDC has connectivity with FSx for ONTAP.

=== Deploy VMware Cloud
https://www.vmware.com/products/vmc-on-aws.html[VMware Cloud on AWS^] provides a cloud-native experience for VMware-based workloads in the AWS ecosystem. Each VMware software-defined data center (SDDC) runs in an Amazon Virtual Private Cloud (VPC) and provides a full VMware stack (including vCenter Server), NSX-T software-defined networking, vSAN software-defined storage, and one or more ESXi hosts that provide compute and storage resources to the workloads. 

To configure a VMC environment on AWS, follow the steps at this https://docs.netapp.com/us-en/netapp-solutions/ehc/aws/aws-setup.html[link^]. A pilot-light cluster can also be used for disaster recovery purposes.

=== Configure Amazon FSx for NetApp ONTAP

Amazon FSx for NetApp ONTAP is a fully managed service that provides highly reliable, scalable, high-performing, and feature-rich file storage built on the popular NetApp ONTAP file system. Follow the steps at this https://docs.netapp.com/us-en/netapp-solutions/ehc/aws/aws-native-overview.html[link^] to provision and configure FSx for NetApp ONTAP.


== Set up BlueXP disaster recovery 
The next step is to set up disaster recovery in BlueXP. 

* Create a Connector in BlueXP.
* Deploy and configure SnapMirror for Amazon FSx for NetApp ONTAP.
* Add the on-premises ONTAP storage working environment to BlueXP. This is the source ONTAP cluster. 
* Add a BlueXP account, add FSxN to the working environment, and add AWS credentials for FSx for ONTAP. 


=== Create a Connector in BlueXP
You need to reach out to your NetApp Sales Rep to try out this service. Then, when you use the BlueXP Connector, it will include the appropriate capabilities for the disaster recovery service. 

To create a Connector in BlueXP before using the service, refer to the BlueXP documentation that describes https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html[how to create a connector^]. 

Use the BlueXP on-premises Connector or the BlueXP AWS Connector, which has access to the source on-premises vCenter and the destination on-premises vCenter.

=== Configure SnapMirror for Amazon FSx for NetApp ONTAP

The next step is to set up disaster recovery in BlueXP. 

. In BlueXP, add an account. Refer to the https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-netapp-accounts.html[BlueXP documentation on how to add an account^]. 
. Add Amazon FSx for NetApp ONTAP to the working environment. Ensure that the SnapMirror relationship with the ONTAP cluster is in place and that it has a destination of FSx for NetApp ONTAP. Refer to https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/use/task-creating-fsx-working-environment.html[how to set up an FSx for ONTAP working environment^].

. In BlueXP, deploy SnapMirror to FSx for NetApp ONTAP.
. In BlueXP, discover the provisioned FSx for NetApp ONTAP on an AWS instance and replicate the specified datastore volumes from an on-premises environment to FSx for NetApp ONTAP with the appropriate frequency and NetApp Snapshot copy retention. 

=== Set up licensing 

With BlueXP disaster recovery, you can sign up for a 90-day free trial.

You can purchase a pay-as-you-go (PAYGO) subscription with AWS Marketplace or Bring Your Own License (BYOL), which is a NetApp License File (NLF).  

For details about setting up licensing for BlueXP disaster recovery, refer to link:../get-started/dr-licensing.html[Set up BlueXP disaster recovery licensing].



