---
sidebar: sidebar
permalink: get-started/dr-setup.html
keywords: bluexp, disaster recovery, aws, amazon web services, amazon fsx for netapp ontap
summary: To use BlueXP disaster recovery, perform a few steps to set it up.    
---

= Set up your infrastructure for BlueXP disaster recovery
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

[.lead]
To use BlueXP disaster recovery, perform a few steps to set it up both in Amazon Web Services (AWS) and in BlueXP.  

TIP: Review link:../get-started/dr-prerequisites.html[prerequisites] to ensure that your environment is ready.

== Get ready for BlueXP disaster recovery for both deployments


* Verify your production environment. 
** Ensure that VMs that you want to protect are hosted on NFS datastores (using ONTAP NFS volumes) or VMFS datastores (using NetApp iSCSI LUNs). 
** Ensure that you have credentials:
*** For your on-premises ONTAP arrays and vCenters, you need credentials. 
*** For onprem to cloud, you need access keys for AWS-hosted VMware cloud instances. 
* Create or verify your disaster recovery site. 
** Create or verify your destination ONTAP SVM. 
** Ensure that your source and destination ONTAP SVMs are peered. 
* Set up vCenter privileges. <link to privileges>.
* Create a DR-specific user account (not the general admin account) and use these privileges.

== Set up DR for onprem to onprem deployments 


== Set up DR for on-premises to AWS


* Set up FSx for ONTAP. 
* Set up VMware Cloud for AWS SDDC. 


 
=== Set up VMware Cloud for AWS SDDC

Set up VMware Cloud for AWS software-defined data center (SDDC).

* Create an Amazon FSx for ONTAP file system. Provision and configure FSx for ONTAP. Amazon FSx for NetApp ONTAP is a fully managed service that provides highly reliable, scalable, high-performing, and feature-rich file storage built on the popular NetApp ONTAP file system. 

* Follow the steps at this https://docs.netapp.com/us-en/netapp-solutions/ehc/aws/aws-native-overview.html[link^] and here https://docs.netapp.com/us-en/bluexp-fsx-ontap/start/task-getting-started-fsx.html[Quick start for Amazon FSx for NetApp ONTAP] to provision and configure FSx for NetApp ONTAP.

* Add Amazon FSx for NetApp ONTAP to the working environment, and add AWS credentials for FSx for ONTAP. 

* In AWS, you'll need to do the following steps: 

** Deploy and configure VMware Cloud on AWS.

** Use a VMware account and provision the SDDC. Ensure that the SDDC has connectivity with FSx for ONTAP.

=== Deploy VMware Cloud
https://www.vmware.com/products/vmc-on-aws.html[VMware Cloud on AWS^] provides a cloud-native experience for VMware-based workloads in the AWS ecosystem. Each VMware software-defined data center (SDDC) runs in an Amazon Virtual Private Cloud (VPC) and provides a full VMware stack (including vCenter Server), NSX-T software-defined networking, vSAN software-defined storage, and one or more ESXi hosts that provide compute and storage resources to the workloads. 

To configure a VMC environment on AWS, follow the steps at this https://docs.netapp.com/us-en/netapp-solutions/ehc/aws/aws-setup.html[link^]. A pilot-light cluster can also be used for disaster recovery purposes.


=== Configure SnapMirror for Amazon FSx for NetApp ONTAP

The next step is to set up configure SnapMirror for Amazon FSx in BlueXP. 

Refer to https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/use/task-creating-fsx-working-environment.html[how to set up an FSx for ONTAP working environment^].

. Add Amazon FSx for NetApp ONTAP to the working environment that is used to manage BlueXP disaster recovery. 
. Ensure the following: 
//** The source and destination clusters are peered. 
//** The destination SVM is created. 
//** The source and destination SVMs are peered. 
//** The SnapMirror relationship with the ONTAP cluster is in place and that it has a destination of FSx for NetApp ONTAP. 

//. In BlueXP, discover the provisioned FSx for NetApp ONTAP on an AWS instance and replicate the specified datastore volumes from an on-premises environment to FSx for NetApp ONTAP with the appropriate frequency and NetApp Snapshot copy retention. 







