---
sidebar: sidebar
permalink: get-started/dr-setup.html
keywords: bluexp, disaster recovery, 
summary: To use BlueXP disaster recovery, perform a few steps to set it up.    
---

= Set up BlueXP disaster recovery
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

[.lead]
To use BlueXP disaster recovery, perform a few steps to set it up.  


* Review link:../get-started/dr-prerequisites.html[prerequisites] to ensure that your environment is ready.
* In AWS: 
** Deploy and configure VMware Cloud on AWS.
** Create an Amazon FSx for ONTAP file system. Provision and configure FSx for ONTAP. 
** Use a VMware account and provision the software-defined data center (SDDC). Ensure that the SDDC has connectivity with FSx for ONTAP.
* In BlueXP: 
** Deploy and configure SnapMirror to FSx for ONTAP
** Add an account, add FSxN to the working environment, and add AWS credentials for FSx for ONTAP. 


== Set up in AWS
In AWS, you'll need to do the following steps: 

* Deploy VMware Cloud
* Configure Amazon FSx for ONTAP

=== In AWS, deploy VMware Cloud 
https://www.vmware.com/products/vmc-on-aws.html[VMware Cloud on AWS^] provides a cloud-native experience for VMware-based workloads in the AWS ecosystem. Each VMware software-defined data center (SDDC) runs in an Amazon Virtual Private Cloud (VPC) and provides a full VMware stack (including vCenter Server), NSX-T software-defined networking, vSAN software-defined storage, and one or more ESXi hosts that provide compute and storage resources to the workloads. 

To configure a VMC environment on AWS, follow the steps at this https://docs.netapp.com/us-en/netapp-solutions/ehc/aws/aws-setup.html[link^]. A pilot-light cluster can also be used for disaster recovery purposes.

=== In AWS, configure FSx for ONTAP

Amazon FSx for NetApp ONTAP is a fully managed service that provides highly reliable, scalable, high-performing, and feature-rich file storage built on the popular NetApp ONTAP file system. Follow the steps at this https://docs.netapp.com/us-en/netapp-solutions/ehc/aws/aws-native-overview.htm[link^] to provision and configure FSx for ONTAP.


== Set up in BlueXP
The next step is to set up disaster recovery in BlueXP. 


=== Create a Connector in BlueXP
A BlueXP Connector includes credentials to NetApp ONTAP machines.

To create a Connector in BlueXP before using the service, refer to the BlueXP documentation that describes https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html[how to create a connector^]. 


=== Deploy and configure SnapMirror to FSx for ONTAP

The next step is to set up disaster recovery in BlueXP. 

. In BlueXP, add an account. Refer to the https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-netapp-accounts.html[BlueXP documentation on how to add an account^]. 
. Add Amazon FSx for ONTAP to the working environment. Ensure that the SnapMirror relationship with the ONTAP cluster is in place and that it has a destination of FSx for ONTAP. Refer to https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/use/task-creating-fsx-working-environment.html[how to set up an FSx for ONTAP working environment^].

. In BlueXP, deploy SnapMirror to FSx for ONTAP.
. In BlueXP, discover the provisioned FSx for ONTAP on an AWS instance and replicate the specified datastore volumes from an on-premises environment to FSx for ONTAP with the appropriate frequency and NetApp Snapshot copy retention. 





