---
sidebar: sidebar
permalink: release-notes/dr-limitations.html
keywords: disaster recovery, bluexp
summary: Known limitations identify platforms, devices, or functions that are not supported by this release of the service, or that do not interoperate correctly with it.
---

= Limitations
:hardbreaks:
:icons: font
:imagesdir: ../media/

[.lead]
Known limitations identify platforms, devices, or functions that are not supported by this release of the service, or that do not interoperate correctly with it.

== BlueXP might not discover Amazon FSx for NetApp ONTAP

Sometimes, BlueXP does not discover Amazon FSx for NetApp ONTAP clusters. 

*Workaround*: Add the Amazon FSx for NetApp ONTAP cluster in BlueXP and periodically refresh the cluster to display any changes. 

If you need to remove the ONTAP FSx cluster from BlueXP disaster recovery service, complete the following steps: 

. In the BlueXP Connector, restart the "occm" service by selecting *docker restart occm*.
. In the BlueXP Canvas, add the Amazon FSx for ONTAP environment again and provide the FSx credentials.
+
Refer to https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/getting-started-step1.html[Create an Amazon FSx for NetApp ONTAP file system^].

. Refresh the FSx discovery in BlueXP disaster recovery. 


